module np_gwas_module:
    snakefile: github("broomej/np-gwas-module", path="Snakefile", tag="v1.0.0")
    config: config

OUTDIR = config["outdir"]["act"]["gwas"]
CONVERT_VCF_OUTDIR = config["outdir"]["act"]["convert_vcf"]
RELATEDNESS_OUTDIR = config["outdir"]["act"]["relatedness_ancestry"]
QC_OUTDIR = config["outdir"]["act"]["sample_variant_qc"]

# Upstream inter-module inputs
PLINK_PFX = f"{CONVERT_VCF_OUTDIR}/results/act_imputed"
PCAIR_B = f"{RELATEDNESS_OUTDIR}/results/2_relatedness_ancestry/pcair_b.rds"
SAMPLE_METRICS = f"{QC_OUTDIR}/results/sample_metrics.rds"

CHROMOSOMES = config["CHROMOSOMES"]
CHROMS_MINUS_X = [c for c in CHROMOSOMES if c != "X"]

use rule gwas from np_gwas_module as gwas_np with:
    input:
        bed=f"{PLINK_PFX}.bed",
        bim=f"{PLINK_PFX}.bim",
        fam=config["fam"],
        covar=config["covar_file"],

rule make_pheno_fam_covar:
    input:
        pcair=PCAIR_B,
        bps="/container/act/act_bps.txt",
        fam=f"{PLINK_PFX}.fam",
        xwalk="/container/act/ACT_ID_xwalk.csv",
        sampmet=SAMPLE_METRICS,
    output:
        covar_file=config["covar_file"],
        fam=config["fam"],
    log: f"{OUTDIR}/logs/make_pheno_fam_covar.log"
    params:
        pheno_name="act_bps",
        covar_names=config["covar_names"],
    script: "scripts/make_pheno.R"

rule plink_freq:
    container: config["images"]["plink"]
    input:
        bed=f"{PLINK_PFX}.bed",
        bim=f"{PLINK_PFX}.bim",
        fam=config["fam"],
    output:
        temp(f"{OUTDIR}/temp/freq/chr{{chromosome}}.frq"),
    log: f"{OUTDIR}/logs/plink_freq/{{chromosome}}.log"
    params:
        chromosome=lambda wildcards: wildcards.chromosome,
    shell:
        """
        outdir=$(dirname {output})
        mkdir -p $outdir
        pfx=$outdir/chr{wildcards.chromosome}
        plink --freq \
            --bed {input.bed} \
            --bim {input.bim} \
            --fam {input.fam} \
            --chr {params.chromosome} \
            --out $pfx
        mv $pfx.frq {output}
        mv $pfx.log {log}
        """

rule change_ids:
    input: f"{OUTDIR}/temp/gwas/chr{{chromosome}}.assoc.linear",
    output: f"{OUTDIR}/results/gwas_id_mapped/chr{{chromosome}}.assoc.linear",
    log: f"{OUTDIR}/logs/change_ids/{{chromosome}}.log"
    script: "scripts/change_ids.R"

rule change_ids_adjust:
    input: f"{OUTDIR}/temp/gwas/chr{{chromosome}}.assoc.linear.adjusted",
    output: f"{OUTDIR}/results/gwas_id_mapped/chr{{chromosome}}.assoc.linear.adjusted",
    log: f"{OUTDIR}/logs/change_ids_adjust/{{chromosome}}.log"
    script: "scripts/change_ids.R"

rule change_freq_ids:
    input: f"{OUTDIR}/temp/freq/chr{{chromosome}}.frq",
    output: f"{OUTDIR}/results/freq_id_mapped/chr{{chromosome}}.frq",
    log: f"{OUTDIR}/logs/change_freq_ids/{{chromosome}}.log"
    script: "scripts/change_ids.R"
