module np_gwas_module:
    #snakefile: github("broomej/np-gwas-module", path="Snakefile", tag="v1.0.0")
    snakefile: "/home/jb/analysis/np-gwas-module/Snakefile"
    config: config

OUTDIR = config["act"]["outdir"]["gwas"]
CONVERT_VCF_OUTDIR = config["act"]["outdir"]["convert_vcf"]
RELATEDNESS_OUTDIR = config["act"]["outdir"]["relatedness_ancestry"]
QC_OUTDIR = config["act"]["outdir"]["sample_variant_qc"]

# Upstream inter-module inputs
PLINK_PFX = f"{CONVERT_VCF_OUTDIR}/results/act_imputed"
PCAIR_B = f"{RELATEDNESS_OUTDIR}/results/2_relatedness_ancestry/pcair_b.rds"
SAMPLE_METRICS = f"{QC_OUTDIR}/results/sample_metrics.rds"

GWAS_OUT_PFX=f"{OUTDIR}/results/act_bps"
rule all:
    input:
        f"{OUTDIR}/results/gwas_id_mapped.assoc.linear",
        f"{OUTDIR}/results/gwas_id_mapped.assoc.linear.adjusted",
        f"{OUTDIR}/results/id_mapped.frq",

FAM_FILE=f"{OUTDIR}/results/formatted.fam"
COVAR_FILE=f"{OUTDIR}/results/formatted.covar"
rule make_pheno_fam_covar:
    container: config["images"]["shiny_verse"]
    input:
        pcair=PCAIR_B,
        bps="/container/act/act_bps.txt",
        fam=f"{PLINK_PFX}.fam",
        xwalk="/container/act/ACT_ID_xwalk.csv",
        sampmet=SAMPLE_METRICS,
    output:
        covar_file=COVAR_FILE,
        fam=FAM_FILE
    log: f"{OUTDIR}/logs/make_pheno_fam_covar.log"
    params:
        pheno_name=config['pheno_name'],
        covar_names=config['covar_names'],
    script: "scripts/make_pheno.R"

use rule gwas from np_gwas_module as gwas_np with:
    container: config["images"]["plink"]
    input:
        bed=f"{PLINK_PFX}.bed",
        bim=f"{PLINK_PFX}.bim",
        fam=FAM_FILE,
        covar=COVAR_FILE,
    output:
        assoc_linear=f"{GWAS_OUT_PFX}.assoc.linear",
        adjusted=f"{GWAS_OUT_PFX}.assoc.linear.adjusted",
    log: f"{GWAS_OUT_PFX}.log" 
    params:
        gwas_output_pfx=GWAS_OUT_PFX
        

FREQ_PFX=f"{OUTDIR}/temp/gwas"
rule plink_freq:
    container: config["images"]["plink"]
    input:
        bed=f"{PLINK_PFX}.bed",
        bim=f"{PLINK_PFX}.bim",
        fam=FAM_FILE,
    output:
        temp(f"{FREQ_PFX}.frq"),
    log: f"{OUTDIR}/logs/plink_freq.log"
    params:
        out_pfx=FREQ_PFX,
    shell:
        """
        outdir=$(dirname {output})
        mkdir -p $outdir
        plink --freq \
            --bed {input.bed} \
            --bim {input.bim} \
            --fam {input.fam} \
            --out {params.out_pfx}
        mv {params.out_pfx}.log {log}
        """

rule change_ids:
    input: f"{GWAS_OUT_PFX}.assoc.linear",
    output: f"{OUTDIR}/results/gwas_id_mapped.assoc.linear",
    log: f"{OUTDIR}/logs/change_ids.log"
    script: "scripts/change_ids.R"

rule change_ids_adjust:
    input: f"{GWAS_OUT_PFX}.assoc.linear.adjusted",
    output: f"{OUTDIR}/results/gwas_id_mapped.assoc.linear.adjusted",
    log: f"{OUTDIR}/logs/change_ids_adjust.log"
    script: "scripts/change_ids.R"

rule change_freq_ids:
    input: f"{FREQ_PFX}.frq",
    output: f"{OUTDIR}/results/id_mapped.frq",
    log: f"{OUTDIR}/logs/change_freq_ids.log"
    script: "scripts/change_ids.R"
